# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-22 06:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod1', models.CharField(max_length=20, verbose_name='نام محصول')),
                ('prod1_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod1_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod2', models.CharField(max_length=20, verbose_name='2نام محصول')),
                ('prod2_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod2_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod3', models.CharField(max_length=20, verbose_name='3نام محصول')),
                ('prod3_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod3_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod4', models.CharField(max_length=20, verbose_name='4نام محصول')),
                ('prod4_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod4_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod5', models.CharField(max_length=20, verbose_name='5نام محصول')),
                ('prod5_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod5_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod6', models.CharField(max_length=20, verbose_name='6نام محصول')),
                ('prod6_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod6_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod7', models.CharField(max_length=20, verbose_name='7نام محصول')),
                ('prod7_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod7_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod8', models.CharField(max_length=20, verbose_name='8نام محصول')),
                ('prod8_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod8_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod9', models.CharField(max_length=20, verbose_name='9نام محصول')),
                ('prod9_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod9_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
                ('prod10', models.CharField(max_length=20, verbose_name='10نام محصول')),
                ('prod10_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('prod10_img', models.ImageField(upload_to='/Users/SAJIPY/Envs/KhoshhalStore/khoshhalistore/media', verbose_name='عکس')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetimefield',
            new_name='createDateTime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.AddField(
            model_name='post',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='matn',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات'),
        ),
    ]
